### ISSUE TITLE
code and datasets 

### ISSUE THREAD

**Issue by Victimmm** [mille-s/PredArg-Template_Extraction#1]
There are no codes or datasets available. Please verify and update accordingly.

**Comment by mille-s** [comment]
Thanks for the ping! I uploaded the code that corresponds to the triple/sentence similarity experiments of the Depling'23 paper. The code of the rest of the pipeline is very messy and is not in a state to be shared now, and unfortunately the funding for the project ended last year. It is unclear at this point when it will be possible to continue it.
